// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCRTJ96jFCB6PhqsRu4fVyVGlkudWM4pk',
    appId: '1:966751407024:web:44edae584eb228ccdda475',
    messagingSenderId: '966751407024',
    projectId: 'sketchapp-ae453',
    authDomain: 'sketchapp-ae453.firebaseapp.com',
    databaseURL: 'https://sketchapp-ae453-default-rtdb.firebaseio.com',
    storageBucket: 'sketchapp-ae453.firebasestorage.app',
    measurementId: 'G-8D6Y39CDLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0doUaRYFVD1Mdkw_oBtaQ8CftTRuWr9E',
    appId: '1:966751407024:android:0f5effe9fb00c5d9dda475',
    messagingSenderId: '966751407024',
    projectId: 'sketchapp-ae453',
    databaseURL: 'https://sketchapp-ae453-default-rtdb.firebaseio.com',
    storageBucket: 'sketchapp-ae453.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6gFVNaPzkLQSsaRpFgsNThLvZFdPJKoI',
    appId: '1:966751407024:ios:43d45114fc763f71dda475',
    messagingSenderId: '966751407024',
    projectId: 'sketchapp-ae453',
    databaseURL: 'https://sketchapp-ae453-default-rtdb.firebaseio.com',
    storageBucket: 'sketchapp-ae453.firebasestorage.app',
    iosBundleId: 'com.example.sketchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6gFVNaPzkLQSsaRpFgsNThLvZFdPJKoI',
    appId: '1:966751407024:ios:43d45114fc763f71dda475',
    messagingSenderId: '966751407024',
    projectId: 'sketchapp-ae453',
    databaseURL: 'https://sketchapp-ae453-default-rtdb.firebaseio.com',
    storageBucket: 'sketchapp-ae453.firebasestorage.app',
    iosBundleId: 'com.example.sketchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCRTJ96jFCB6PhqsRu4fVyVGlkudWM4pk',
    appId: '1:966751407024:web:3d735e6db3e69acedda475',
    messagingSenderId: '966751407024',
    projectId: 'sketchapp-ae453',
    authDomain: 'sketchapp-ae453.firebaseapp.com',
    databaseURL: 'https://sketchapp-ae453-default-rtdb.firebaseio.com',
    storageBucket: 'sketchapp-ae453.firebasestorage.app',
    measurementId: 'G-JRVZS1EPC7',
  );
}
